### ISSUE TITLE
Design and Build KPT: Bio Page

### ISSUE THREAD

**Issue by bnaolu** [Bixal/rapid-response-team#30]
- [x] Design in Figma
- [x] Build in Codepen
- [x] Review

**Comment by kbchumley** [comment]
in progress in codepen

**Comment by kbchumley** [comment]
@bnaolu  @pglevy  The[ bio template in codepen](https://codepen.io/kbchumley/pen/qBrZJYB?editors=1000) is ready for review! 

Changes Made: 
- spacing between contact information
- margin tweak to make sure paragraph aligns with image in desktop
- section closing tag was missing so i added that back in
- grid-col changed from 50/50 split to the image at a grid-col-7 and the paragraph to a grid-col-5
- gave the individual contact info its own divs to live within
- button changed to say "connect on linkedin"

**Comment by kbchumley** [comment]
@bnaolu @pglevy I made changes to the [codepen](https://codepen.io/kbchumley/pen/qBrZJYB?editors=1000) based off Philips feedback! 

**Changes made:** 

- removed unnecessary divs 
- took away use of margin and padding at the same time and only used margin 
- took away unnecessary section id
- added javascript:void(0) to replace #
- took away unused utility class on image

**Comment by bnaolu** [comment]
This looks so good, @kbchumley!
