### ISSUE TITLE
Design and Build KPT: Article Page

### ISSUE THREAD

**Issue by bnaolu** [Bixal/rapid-response-team#34]
- [x] Design in [Figma](https://www.figma.com/file/s0zKIEPUh1k0oW4FDvVeIb/USWDS-Templates-Truss-Lib-v2.10.0?node-id=5%3A1)
- [x] Build in [Codepen](https://codepen.io/pglevy/pen/wvgjyzr?editors=1000)
- [x] Review

**Comment by pglevy** [comment]
Finished getting content into figma and adjusting header and footer symbols. (We can clean these up for reuse later.)

Ready for review.

**Comment by bnaolu** [comment]
Reviewed! This looks really good! 
- [x] Shippable
