### ISSUE TITLE
Capture template tips in wiki

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#36]
Instead of capturing in Word, let's capture the tips that come out of Teams discussions in the wiki instead. Maybe start a "tips" section on the [Templates page](https://github.com/Bixal/rapid-response-team/wiki/Templates). Or something else if that makes sense.

**Comment by bnaolu** [comment]
@pglevy @kbchumley
Added the few tips I took from our Teams channel. Feel free to reword or tweak something if it sounds off.

**Comment by pglevy** [comment]
Great start! We'll add to this as needed. Closing this issue.
