### ISSUE TITLE
KPT: Team

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#37]
- [x] figma
- [x] code

**Comment by pglevy** [comment]
@Bixal/rapid-response, Team template ready for review in [figma](https://www.figma.com/file/s0zKIEPUh1k0oW4FDvVeIb/USWDS-Templates-Truss-Lib-v2.10.0?node-id=642%3A2371).

**Comment by bnaolu** [comment]
Reviewed! 👍🏻  I have no complaints, it looks great!
