### ISSUE TITLE
KPT: Video

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#41]
- [x] figma
- [x] codepen
- [x] move to GH

**Comment by bnaolu** [comment]
Figma completed and ready for review.

**Comment by pglevy** [comment]
Left a few minor comments in figma. When finished, can you add the link to the mobile board to the page templates repo so it takes you there?

**Comment by pglevy** [comment]
tweaks to spacing, and replaced breadcrumb on small screen

**Comment by bnaolu** [comment]
> Left a few minor comments in figma. When finished, can you add the link to the mobile board to the page templates repo so it takes you there?

Added the Figma mobile frame link to repo.
