### ISSUE TITLE
Run initial usability tests for Complaint Screener template

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#51]
What we want to know:

- Can non-developers figure it out and use this tool?
- What problems or questions do they run into?

Who we should test:

- Two designers who maybe have already created GH accounts but are not super familiar with the platform.
- One aspiring developer (I have a potential candidate.)

What needs to be done for this issue:

- Write up a basic test plan/script.
- Schedule people and run tests.
- Share out high-level findings (and links to recordings).

**Comment by bnaolu** [comment]
FigJam [journey maps](https://www.figma.com/file/63P1Gh2L4CmhGNOShtZBF1/User-Journey-Map-Template-(Community)?node-id=0%3A1) from first round of usability testings.
Summary of most important issues to address next can be viewed there, as well.
