### ISSUE TITLE
Make updates to Complaint Screener and get feedback

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#64]

**Comment by bnaolu** [comment]
@pglevy, if you want to review their code for the image issue:
- [Briana's repo](https://github.com/bischoffbri/test)
- [Kelsey's repo](https://github.com/kwilbon/my-screener)

**Comment by bnaolu** [comment]
Second round testing [summary](https://www.figma.com/file/63P1Gh2L4CmhGNOShtZBF1/Screener-Prototype-User-Journey-Maps?node-id=0%3A1) ready! :) Located on the right-side of the first round summaries.

**Comment by pglevy** [comment]
Closing this out since we have two rounds of feedback and summary. We'll track a case study write-up and next steps separately.
