### ISSUE TITLE
Shaping: navigation test drive

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#65]
Validate idea from discussion #58 

General idea: Let's set up a product page that looks like a legit SaaS product, not related to something we're doing. This way we can send the link to some UXers and content people and see what their actual feedback is.

How we can do it:

- Use this [free Jekyll theme](https://jekyllthemes.io/theme/hydra-jekyll-theme)
  - [Live demo](https://pglevy.github.io/hydra-jekyll-template/)
- Set it up as an [organization site](https://pages.github.com/#user-site) using one of our personal accounts
- Come up with a name
- Come up with marketing copy and feature highlights
- Add in a few custom illustrations

Product page inspiration:
- [Square](https://squareup.com/us/en)
- [Heurio](https://www.heurio.co/)
- [Optimal Workshop](https://www.optimalworkshop.com/)
- [Crazy Egg](https://www.crazyegg.com/)

Test drive inspiration:
- [Mini](https://www.miniusa.com/tools/shopping/schedule-a-test-drive.html)
- [Tesla](https://www.tesla.com/en_IE/support/touchless-test-drive?redirect=no&123=)
- [Toyota](https://www.toyota.com/rental/car-tips/Drive-to-Decide-Extend-Your-Test-Drive-Before-Buying-a-Car.html)

**Comment by bnaolu** [comment]
Loving this already. Can't wait to start working on this, come Monday! 🤩

**Comment by pglevy** [comment]
Some copy ideas I was playing with this morning...

- Site Nav Test Drive
- Website Steering Wheel
- Try your new nav on the old site. No code required.
- Kick the tires on your navigation ideas on the live site.
- Will your new navigation ideas go the distance? Take it for a spin on your current site.
- Get that new nav smell before your site even hits the production line.
- Try (rent) before you buy... See what the kids think... Click before you code.

[Tell me more](#)

Benefits:
- Try out new navigation with testers in realtime on a working site.
- Validate card sorts and tree jacks with qualitative research.
- Work out thorny information architecture issues before your team starts coding.
- Work out IA speed bumps before...

Features/How it works:
- Define your new nav labels with links to the current site.
- Enter the address of your current site.
- Set the amount of overlap you need to cover the current nav.

You now have a working navigation component layered on top of the current site that testers can use to experience the current content in a new way!

Wanna take it for a spin? Send us an email and we'll get you early access.
Wanna kick the tires?

[I'm interested](#)

**Comment by pglevy** [comment]
Some feedback from a content strategist and ux researcher/designer:

> Yeah, sounds like a cool idea. I was curious. I like the idea of being able to overlay a new navigation and see how it might work ...

> Generally I dig the idea of doing a tree test in context of the actual site.

> We're planning to set up a tree test and have them and users do it, but something like this would provide richer data because we'd capture insights about the interface challenges that might also hinder someone finding a page

> clients get stuck in their thinking, and this is an interesting, incremental way to introduce new ideas

**Comment by bnaolu** [comment]
That is awesome feedback! I'm hopeful! 🥲

**Comment by pglevy** [comment]
Site we came up with to validate the idea: [live](https://sitenavtestdrive.github.io/), [repo](https://github.com/sitenavtestdrive/sitenavtestdrive.github.io)
