### ISSUE TITLE
Draft communication plan

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#8]
What to include:

- goals
- stakeholders
- channels and methods

**Comment by pglevy** [comment]
@Bixal/rapid-response, [here's a start](https://github.com/Bixal/rapid-response-team/wiki/Communications-plan). This doesn't have to be complete for this cycle, but wanted to get feedback on this first pass.

**Comment by pglevy** [comment]
My thought is to do all of these for each project, so instead of trying to remember and compile things after the fact, we have lots of readymade content about our work available for whatever comes up (lightning talks, presentations, blog posts, etc.). It could certainly be a group effort, but maybe we rotate who's on point or who does the first draft, or something like that.

**Comment by bnaolu** [comment]
Just finished reading through the plan and it sounds great so far!

**Comment by pglevy** [comment]
Cool, we'll go with this for now and see how we do with a write-up for med-cat-supply.
