### ISSUE TITLE
Extract page templates from DPC Design Challenge for reuse...

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#98]
Let's only tackle 1 or 2 for this cycle.

Should follow patterns established with existing page templates.

Recommend starting with code and then refining in Figma as needed.

**Comment by bnaolu** [comment]
Refer to this [PR](https://github.com/Bixal/uswds-page-templates/pull/44), please and thank you 😊

**Comment by pglevy** [comment]
Done! https://bixal.github.io/uswds-page-templates/pages/tasks-status.html
