### ISSUE TITLE
Prep for USWDS Design Token Guide preso...

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#99]
- [ ] Outline and/or slides
- [ ] Tidy up project as needed

**Comment by demi-johnson** [comment]
Started on an outline [here](https://bixal365-my.sharepoint.com/:w:/g/personal/demi_johnson_bixal_com/EcyXP4bYUNBFjkPLNuY9ak8BC1x9gbCBg4nA3_irROHvOA?e=5a2U2p)
